# Generated by Django 5.1 on 2024-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data of Birth (ex:yyyy-mm-dd)'),
        ),
    ]
