# Generated by Django 5.1 on 2024-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_app', '0002_alter_accounts_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('female', 'female')], default='none', max_length=100),
        ),
    ]
