# Generated by Django 5.1 on 2024-08-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_app', '0003_accounts_age_accounts_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('', 'select'), ('male', 'male'), ('female', 'female'), ('female', 'female')], default='none', max_length=100),
        ),
    ]
